version: '3'
services:
  webserver:
    build:
      context: .
      dockerfile: apache-php-dockerfile
    volumes:
      - ./src/:/var/www/html/
    ports: 
      - "80:80"
      - "443:443"
    networks: 
      - dev
  backend:
    image: mysql:8.0.18
    container_name: db
    environment: 
      MYSQL_ROOT_PASSWORD: 'NOTPRODUCTION'
    volumes:
     - mysql:/var/lib/mysql
    networks:
      - dev
    command: --default-authentication-plugin=mysql_native_password
  admin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
    - "8080:80"
    environment: 
      PMA_HOST: db
    depends_on:
      - backend
    networks:
     - dev
networks: 
  dev:
volumes:
  mysql: